version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432"
  web:
    build: .
    env_file:
      - .env
    command: bash -c "(bundle check || bundle install) && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/donatio
    ports:
      - "3000:3000"
    depends_on:
      - postgres
